name: 'Complicated Webhook Message'
description: 'Post a message with optional image and extra text blocks into a Teams channel using workflows'
author: 'hoonga'
branding:
  icon: 'message-square'
  color: 'blue'

inputs:
  message_title:
    description: 'Title of the message'
    required: true
  message_description:
    description: 'Description of the message'
    required: true
  webhook:
    description: 'Webhook URL for the Teams channel'
    required: true
  status:
    description: ''

# Check https://adaptivecards.io/designer/ for making templates
# Also check https://amdesigner.azurewebsites.net/ for more examples
runs:
  using: "composite"
  steps:
    - name: teams-message
      shell: bash
      env:
        TEAMS_WEBHOOK: ${{ inputs.webhook }}
      run: |

        CARD_JSON=$(cat << EOF
        {
          "type": "message",
          "attachments": [
            {
              "contentType": "application/vnd.microsoft.card.adaptive",
              "contentUrl": null,
              "content": {
                  "type": "AdaptiveCard",
                  "body": [
                      {
                          "type": "Container",
                          "items": [
                              {
                                  "type": "TextBlock",
                                  "text": "${{inputs.title}}",
                                  "wrap": true,
                                  "style": "heading"
                              }
                          ],
                          "bleed": true,
                          "separator": true,
                          "style": "good"
                      },
                      {
                          "type": "Container",
                          "padding": "Default",
                          "spacing": "None",
                          "items": [
                              {
                                  "type": "TextBlock",
                                  "text": "${{inputs.detail}}",
                                  "wrap": true,
                                  "weight": "Bolder",
                                  "size": "Large",
                                  "style": "heading"
                              },
                              {
                                  "type": "TextBlock",
                                  "text": "commit message",
                                  "wrap": true
                              },
                              {
                                  "type": "ActionSet",
                                  "id": "c8a5ba7e-7ec6-53ae-79da-0cfb952a527e",
                                  "actions": [
                                      {
                                          "type": "Action.OpenUrl",
                                          "title": "개발사항",
                                          "tooltip": "개발사항",
                                          "iconUrl": "http",
                                          "url": "https://github.com"
                                      },
                                      {
                                          "type": "Action.OpenUrl",
                                          "title": "코드 변경 내역",
                                          "tooltip": "코드 변경 내역",
                                          "iconUrl": "http",
                                          "url": "https://github.com"
                                      },
                                      {
                                          "type": "Action.OpenUrl",
                                          "title": "Workflow 확인",
                                          "tooltip": "Workflow 확인",
                                          "iconUrl": "http",
                                          "url": "https://github.com"
                                      }
                                  ]
                              }
                          ]
                      }
                  ],
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "version": "1.5"
              }
            }
          ]
        }
        EOF
        )

        # Send the Adaptive Card to Teams
        curl -H "Content-Type: application/json" -d "$CARD_JSON" $TEAMS_WEBHOOK